/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContactView: typeof import('./src/components/ContactView.vue')['default']
    FooterView: typeof import('./src/components/FooterView.vue')['default']
    FriendsView: typeof import('./src/components/FriendsView.vue')['default']
    Lantern: typeof import('./src/components/Lantern.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sentence: typeof import('./src/components/Sentence.vue')['default']
    SkillsView: typeof import('./src/components/SkillsView.vue')['default']
    StarTrails: typeof import('./src/components/StarTrails.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    Typed: typeof import('./src/components/Typed.vue')['default']
  }
}
