/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Contact: typeof import('./src/components/Contact.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Friends: typeof import('./src/components/Friends.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    Skills: typeof import('./src/components/Skills.vue')['default']
    StarTrails: typeof import('./src/components/StarTrails.vue')['default']
    Yulu: typeof import('./src/components/Yulu.vue')['default']
  }
}
