name: Deploy Website

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '8.0.0'

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build project
        run: |
          pnpm build
          echo "Build completed. Listing files:"
          ls -R

      - name: Zip the dist directory
        run: |
          zip -r ./website-build.zip ./dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            ./website-build.zip
